# -*- coding: utf-8 -*-
"""lab-1\.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Su-Ezo6w_CbTkqJCCd6aC8GMiJA_S7kz
"""

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error


def linear_model_analysis(x, y, test_value):
    model = LinearRegression()
    model.fit(x, y)

    predictions = model.predict(x)
    test_pred = model.predict(test_value)

    mse = mean_squared_error(y, predictions)

    print("Linear Regression Model")
    print(f"Equation: y = {model.intercept_:.2f} + {model.coef_[0]:.2f}x")
    print(f"Prediction for x=6: {test_pred[0]}")
    print(f"MSE: {mse}\n")


def polynomial_model_analysis(x, y, test_value, degree=4):
    poly_features = PolynomialFeatures(degree=degree)
    x_transformed = poly_features.fit_transform(x)

    model = LinearRegression()
    model.fit(x_transformed, y)

    predictions = model.predict(x_transformed)
    test_pred = model.predict(poly_features.transform(test_value))

    mse = mean_squared_error(y, predictions)

    print(f"Polynomial Regression Model (Degree {degree})")
    print(f"Prediction for x=6: {test_pred[0]}")
    print(f"MSE: {mse}\n")


# Dataset
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
y = np.array([52, 55, 61, 70, 82])
x_test = np.array([[6]])

# Model executions
linear_model_analysis(X, y, x_test)
polynomial_model_analysis(X, y, x_test)

# Bias–Variance explanation
print("Bias–Variance Tradeoff")
print("Linear Model  : High Bias, Low Variance")
print("Polynomial Model: Low Bias, High Variance")